version: '3'
services:
  mongo-db:
    image: mongo
    ports:
      - 27017:27017
  client-app:
    build: ./jv-gomuku-app
    environment:
      - REACT_APP_PROXY_HOST=http://server-app:8080
    volumes:
      - ./jv-gomuku-app/src:/jv-gomuku-app/src
      - ./jv-gomuku-app/public:/jv-gomuku-app/public
    ports:
      - 3000:3000
  server-app:
    build: ./jv-gomuku-service
    environment:
      - dbURI=mongodb://mongo-db:27017
      - allowHost=http://localhost:3000
    volumes:
      - ./jv-gomuku-service/src:/jv-gomuku-service/src
    ports:
      - 8080:8080